# Select image from https://hub.docker.com/_/php/
image: php:8.2

# Select what we should cache
cache:
  paths:
    - vendor/

before_script:
  # Install git, postgres and zip library, the php image doesn't have installed
  - apt update -yqq
  - apt install git libpq-dev libzip-dev zip -yqq

  # Install database driver and zip
  - docker-php-ext-install pdo_mysql pdo_pgsql zip

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install

stages:
  - test
  - deploy

test:
  stage: test
  image: php:8.2
  script:
    - vendor/bin/phpunit tests/

deploy:
  stage: deploy
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=<tag> "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  environment: production